version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"  # This line is not needed when using host network mode
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    network_mode: "host"  # Add this line to use the host network